name: Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: configure
      run: cmake -Bbuild -DENABLE_UNIT_TESTING=0
      
    - name: build
      run: cmake --build build --config Release
