name: Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release
  INSTALL_LOCATION: .local

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: cache dependencies
      uses: actions/cache@v2
      id: cache-dependencies
      with:
        path: ${{github.workspace}}/${{env.INSTALL_LOCATION}}
        key: ${{runner.os}}-${{hashFiles($env.INSTALL_LOCATION)}}

    - name: install GoogleTest
      if: steps.cache.output.cache-hit != 'true'
      run: |
        mkdir $GITHUB_WORKSPACE/$INSTALL_LOCATION
        cd ..
        git clone https://github.com/google/googletest.git --branch release-1.10.0
        cd googletest
        cmake -Bbuild -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/$INSTALL_LOCATION -Dgtest_force_shared_crt=1
        cmake --build build --config Debug
        cmake --build build --config Release
        cmake --build build --target install --config Debug
        cmake --build build --target install --config Release
        cd ../modern-cpp-template

    - name: configure
      run: cmake -Bbuild -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/$INSTALL_LOCATION
      
    - name: build
      run: cmake --build build --config $BUILD_TYPE -j4

    - name: run tests
      run: |
        cd build
        ctest -C $BUILD_TYPE
